// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.2
// source: api/base/v1/base.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateBaseRequest) Reset() {
	*x = CreateBaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_base_v1_base_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBaseRequest) ProtoMessage() {}

func (x *CreateBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_v1_base_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBaseRequest.ProtoReflect.Descriptor instead.
func (*CreateBaseRequest) Descriptor() ([]byte, []int) {
	return file_api_base_v1_base_proto_rawDescGZIP(), []int{0}
}

type CreateBaseReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateBaseReply) Reset() {
	*x = CreateBaseReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_base_v1_base_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBaseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBaseReply) ProtoMessage() {}

func (x *CreateBaseReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_v1_base_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBaseReply.ProtoReflect.Descriptor instead.
func (*CreateBaseReply) Descriptor() ([]byte, []int) {
	return file_api_base_v1_base_proto_rawDescGZIP(), []int{1}
}

type UpdateBaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateBaseRequest) Reset() {
	*x = UpdateBaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_base_v1_base_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBaseRequest) ProtoMessage() {}

func (x *UpdateBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_v1_base_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBaseRequest.ProtoReflect.Descriptor instead.
func (*UpdateBaseRequest) Descriptor() ([]byte, []int) {
	return file_api_base_v1_base_proto_rawDescGZIP(), []int{2}
}

type UpdateBaseReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateBaseReply) Reset() {
	*x = UpdateBaseReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_base_v1_base_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBaseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBaseReply) ProtoMessage() {}

func (x *UpdateBaseReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_v1_base_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBaseReply.ProtoReflect.Descriptor instead.
func (*UpdateBaseReply) Descriptor() ([]byte, []int) {
	return file_api_base_v1_base_proto_rawDescGZIP(), []int{3}
}

type DeleteBaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteBaseRequest) Reset() {
	*x = DeleteBaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_base_v1_base_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBaseRequest) ProtoMessage() {}

func (x *DeleteBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_v1_base_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBaseRequest.ProtoReflect.Descriptor instead.
func (*DeleteBaseRequest) Descriptor() ([]byte, []int) {
	return file_api_base_v1_base_proto_rawDescGZIP(), []int{4}
}

type DeleteBaseReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteBaseReply) Reset() {
	*x = DeleteBaseReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_base_v1_base_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBaseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBaseReply) ProtoMessage() {}

func (x *DeleteBaseReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_v1_base_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBaseReply.ProtoReflect.Descriptor instead.
func (*DeleteBaseReply) Descriptor() ([]byte, []int) {
	return file_api_base_v1_base_proto_rawDescGZIP(), []int{5}
}

type GetBaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetBaseRequest) Reset() {
	*x = GetBaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_base_v1_base_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBaseRequest) ProtoMessage() {}

func (x *GetBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_v1_base_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBaseRequest.ProtoReflect.Descriptor instead.
func (*GetBaseRequest) Descriptor() ([]byte, []int) {
	return file_api_base_v1_base_proto_rawDescGZIP(), []int{6}
}

type GetBaseReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetBaseReply) Reset() {
	*x = GetBaseReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_base_v1_base_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBaseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBaseReply) ProtoMessage() {}

func (x *GetBaseReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_v1_base_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBaseReply.ProtoReflect.Descriptor instead.
func (*GetBaseReply) Descriptor() ([]byte, []int) {
	return file_api_base_v1_base_proto_rawDescGZIP(), []int{7}
}

type ListBaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListBaseRequest) Reset() {
	*x = ListBaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_base_v1_base_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBaseRequest) ProtoMessage() {}

func (x *ListBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_v1_base_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBaseRequest.ProtoReflect.Descriptor instead.
func (*ListBaseRequest) Descriptor() ([]byte, []int) {
	return file_api_base_v1_base_proto_rawDescGZIP(), []int{8}
}

type ListBaseReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListBaseReply) Reset() {
	*x = ListBaseReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_base_v1_base_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBaseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBaseReply) ProtoMessage() {}

func (x *ListBaseReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_v1_base_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBaseReply.ProtoReflect.Descriptor instead.
func (*ListBaseReply) Descriptor() ([]byte, []int) {
	return file_api_base_v1_base_proto_rawDescGZIP(), []int{9}
}

var File_api_base_v1_base_proto protoreflect.FileDescriptor

var file_api_base_v1_base_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x61,
	0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x61,
	0x73, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x13, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x13, 0x0a,
	0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x13, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x10, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x0e, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x11, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x32, 0xf3, 0x02, 0x0a, 0x04, 0x42, 0x61, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0a,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x65, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4a, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x42, 0x61, 0x73, 0x65, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x61, 0x73,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x61, 0x73,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x4a, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61,
	0x73, 0x65, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x41, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x65, 0x12, 0x1b, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62,
	0x61, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x44, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x61, 0x73, 0x65, 0x12,
	0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x2b, 0x0a, 0x0b, 0x61, 0x70, 0x69,
	0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x1a, 0x73, 0x74, 0x62, 0x2d,
	0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x61, 0x73, 0x65,
	0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_base_v1_base_proto_rawDescOnce sync.Once
	file_api_base_v1_base_proto_rawDescData = file_api_base_v1_base_proto_rawDesc
)

func file_api_base_v1_base_proto_rawDescGZIP() []byte {
	file_api_base_v1_base_proto_rawDescOnce.Do(func() {
		file_api_base_v1_base_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_base_v1_base_proto_rawDescData)
	})
	return file_api_base_v1_base_proto_rawDescData
}

var file_api_base_v1_base_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_base_v1_base_proto_goTypes = []interface{}{
	(*CreateBaseRequest)(nil), // 0: api.base.v1.CreateBaseRequest
	(*CreateBaseReply)(nil),   // 1: api.base.v1.CreateBaseReply
	(*UpdateBaseRequest)(nil), // 2: api.base.v1.UpdateBaseRequest
	(*UpdateBaseReply)(nil),   // 3: api.base.v1.UpdateBaseReply
	(*DeleteBaseRequest)(nil), // 4: api.base.v1.DeleteBaseRequest
	(*DeleteBaseReply)(nil),   // 5: api.base.v1.DeleteBaseReply
	(*GetBaseRequest)(nil),    // 6: api.base.v1.GetBaseRequest
	(*GetBaseReply)(nil),      // 7: api.base.v1.GetBaseReply
	(*ListBaseRequest)(nil),   // 8: api.base.v1.ListBaseRequest
	(*ListBaseReply)(nil),     // 9: api.base.v1.ListBaseReply
}
var file_api_base_v1_base_proto_depIdxs = []int32{
	0, // 0: api.base.v1.Base.CreateBase:input_type -> api.base.v1.CreateBaseRequest
	2, // 1: api.base.v1.Base.UpdateBase:input_type -> api.base.v1.UpdateBaseRequest
	4, // 2: api.base.v1.Base.DeleteBase:input_type -> api.base.v1.DeleteBaseRequest
	6, // 3: api.base.v1.Base.GetBase:input_type -> api.base.v1.GetBaseRequest
	8, // 4: api.base.v1.Base.ListBase:input_type -> api.base.v1.ListBaseRequest
	1, // 5: api.base.v1.Base.CreateBase:output_type -> api.base.v1.CreateBaseReply
	3, // 6: api.base.v1.Base.UpdateBase:output_type -> api.base.v1.UpdateBaseReply
	5, // 7: api.base.v1.Base.DeleteBase:output_type -> api.base.v1.DeleteBaseReply
	7, // 8: api.base.v1.Base.GetBase:output_type -> api.base.v1.GetBaseReply
	9, // 9: api.base.v1.Base.ListBase:output_type -> api.base.v1.ListBaseReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_base_v1_base_proto_init() }
func file_api_base_v1_base_proto_init() {
	if File_api_base_v1_base_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_base_v1_base_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_base_v1_base_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBaseReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_base_v1_base_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_base_v1_base_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBaseReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_base_v1_base_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_base_v1_base_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBaseReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_base_v1_base_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_base_v1_base_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBaseReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_base_v1_base_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_base_v1_base_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBaseReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_base_v1_base_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_base_v1_base_proto_goTypes,
		DependencyIndexes: file_api_base_v1_base_proto_depIdxs,
		MessageInfos:      file_api_base_v1_base_proto_msgTypes,
	}.Build()
	File_api_base_v1_base_proto = out.File
	file_api_base_v1_base_proto_rawDesc = nil
	file_api_base_v1_base_proto_goTypes = nil
	file_api_base_v1_base_proto_depIdxs = nil
}
