// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.22.3
// source: api/base/v1/err.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateErrRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateErrRequest) Reset() {
	*x = CreateErrRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_base_v1_err_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateErrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateErrRequest) ProtoMessage() {}

func (x *CreateErrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_v1_err_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateErrRequest.ProtoReflect.Descriptor instead.
func (*CreateErrRequest) Descriptor() ([]byte, []int) {
	return file_api_base_v1_err_proto_rawDescGZIP(), []int{0}
}

type CreateErrReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateErrReply) Reset() {
	*x = CreateErrReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_base_v1_err_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateErrReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateErrReply) ProtoMessage() {}

func (x *CreateErrReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_v1_err_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateErrReply.ProtoReflect.Descriptor instead.
func (*CreateErrReply) Descriptor() ([]byte, []int) {
	return file_api_base_v1_err_proto_rawDescGZIP(), []int{1}
}

type UpdateErrRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateErrRequest) Reset() {
	*x = UpdateErrRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_base_v1_err_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateErrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateErrRequest) ProtoMessage() {}

func (x *UpdateErrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_v1_err_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateErrRequest.ProtoReflect.Descriptor instead.
func (*UpdateErrRequest) Descriptor() ([]byte, []int) {
	return file_api_base_v1_err_proto_rawDescGZIP(), []int{2}
}

type UpdateErrReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateErrReply) Reset() {
	*x = UpdateErrReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_base_v1_err_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateErrReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateErrReply) ProtoMessage() {}

func (x *UpdateErrReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_v1_err_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateErrReply.ProtoReflect.Descriptor instead.
func (*UpdateErrReply) Descriptor() ([]byte, []int) {
	return file_api_base_v1_err_proto_rawDescGZIP(), []int{3}
}

type DeleteErrRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteErrRequest) Reset() {
	*x = DeleteErrRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_base_v1_err_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteErrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteErrRequest) ProtoMessage() {}

func (x *DeleteErrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_v1_err_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteErrRequest.ProtoReflect.Descriptor instead.
func (*DeleteErrRequest) Descriptor() ([]byte, []int) {
	return file_api_base_v1_err_proto_rawDescGZIP(), []int{4}
}

type DeleteErrReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteErrReply) Reset() {
	*x = DeleteErrReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_base_v1_err_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteErrReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteErrReply) ProtoMessage() {}

func (x *DeleteErrReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_v1_err_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteErrReply.ProtoReflect.Descriptor instead.
func (*DeleteErrReply) Descriptor() ([]byte, []int) {
	return file_api_base_v1_err_proto_rawDescGZIP(), []int{5}
}

type GetErrRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetErrRequest) Reset() {
	*x = GetErrRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_base_v1_err_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetErrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetErrRequest) ProtoMessage() {}

func (x *GetErrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_v1_err_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetErrRequest.ProtoReflect.Descriptor instead.
func (*GetErrRequest) Descriptor() ([]byte, []int) {
	return file_api_base_v1_err_proto_rawDescGZIP(), []int{6}
}

type GetErrReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetErrReply) Reset() {
	*x = GetErrReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_base_v1_err_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetErrReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetErrReply) ProtoMessage() {}

func (x *GetErrReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_v1_err_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetErrReply.ProtoReflect.Descriptor instead.
func (*GetErrReply) Descriptor() ([]byte, []int) {
	return file_api_base_v1_err_proto_rawDescGZIP(), []int{7}
}

type ListErrRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListErrRequest) Reset() {
	*x = ListErrRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_base_v1_err_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListErrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListErrRequest) ProtoMessage() {}

func (x *ListErrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_v1_err_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListErrRequest.ProtoReflect.Descriptor instead.
func (*ListErrRequest) Descriptor() ([]byte, []int) {
	return file_api_base_v1_err_proto_rawDescGZIP(), []int{8}
}

type ListErrReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListErrReply) Reset() {
	*x = ListErrReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_base_v1_err_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListErrReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListErrReply) ProtoMessage() {}

func (x *ListErrReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_v1_err_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListErrReply.ProtoReflect.Descriptor instead.
func (*ListErrReply) Descriptor() ([]byte, []int) {
	return file_api_base_v1_err_proto_rawDescGZIP(), []int{9}
}

var File_api_base_v1_err_proto protoreflect.FileDescriptor

var file_api_base_v1_err_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x72,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x61, 0x73,
	0x65, 0x2e, 0x76, 0x31, 0x22, 0x12, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x72,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x45, 0x72, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x12, 0x0a, 0x10, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x45, 0x72, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x10,
	0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x72, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x12, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x72, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x72,
	0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x0f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x45, 0x72, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0d, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x45, 0x72,
	0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x10, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x72,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74,
	0x45, 0x72, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xe3, 0x02, 0x0a, 0x03, 0x45, 0x72, 0x72,
	0x12, 0x47, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x72, 0x72, 0x12, 0x1d, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x45, 0x72, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x45, 0x72, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x47, 0x0a, 0x09, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x45, 0x72, 0x72, 0x12, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x61, 0x73,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x72, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x61, 0x73, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x72, 0x72, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x47, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x72, 0x72, 0x12,
	0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x45, 0x72, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x45, 0x72, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3e, 0x0a, 0x06, 0x47,
	0x65, 0x74, 0x45, 0x72, 0x72, 0x12, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x61, 0x73, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x72, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x45, 0x72, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x41, 0x0a, 0x07, 0x4c,
	0x69, 0x73, 0x74, 0x45, 0x72, 0x72, 0x12, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x61, 0x73,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x72, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x72, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x2b,
	0x0a, 0x0b, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a,
	0x1a, 0x73, 0x74, 0x62, 0x2d, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_api_base_v1_err_proto_rawDescOnce sync.Once
	file_api_base_v1_err_proto_rawDescData = file_api_base_v1_err_proto_rawDesc
)

func file_api_base_v1_err_proto_rawDescGZIP() []byte {
	file_api_base_v1_err_proto_rawDescOnce.Do(func() {
		file_api_base_v1_err_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_base_v1_err_proto_rawDescData)
	})
	return file_api_base_v1_err_proto_rawDescData
}

var file_api_base_v1_err_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_base_v1_err_proto_goTypes = []interface{}{
	(*CreateErrRequest)(nil), // 0: api.base.v1.CreateErrRequest
	(*CreateErrReply)(nil),   // 1: api.base.v1.CreateErrReply
	(*UpdateErrRequest)(nil), // 2: api.base.v1.UpdateErrRequest
	(*UpdateErrReply)(nil),   // 3: api.base.v1.UpdateErrReply
	(*DeleteErrRequest)(nil), // 4: api.base.v1.DeleteErrRequest
	(*DeleteErrReply)(nil),   // 5: api.base.v1.DeleteErrReply
	(*GetErrRequest)(nil),    // 6: api.base.v1.GetErrRequest
	(*GetErrReply)(nil),      // 7: api.base.v1.GetErrReply
	(*ListErrRequest)(nil),   // 8: api.base.v1.ListErrRequest
	(*ListErrReply)(nil),     // 9: api.base.v1.ListErrReply
}
var file_api_base_v1_err_proto_depIdxs = []int32{
	0, // 0: api.base.v1.Err.CreateErr:input_type -> api.base.v1.CreateErrRequest
	2, // 1: api.base.v1.Err.UpdateErr:input_type -> api.base.v1.UpdateErrRequest
	4, // 2: api.base.v1.Err.DeleteErr:input_type -> api.base.v1.DeleteErrRequest
	6, // 3: api.base.v1.Err.GetErr:input_type -> api.base.v1.GetErrRequest
	8, // 4: api.base.v1.Err.ListErr:input_type -> api.base.v1.ListErrRequest
	1, // 5: api.base.v1.Err.CreateErr:output_type -> api.base.v1.CreateErrReply
	3, // 6: api.base.v1.Err.UpdateErr:output_type -> api.base.v1.UpdateErrReply
	5, // 7: api.base.v1.Err.DeleteErr:output_type -> api.base.v1.DeleteErrReply
	7, // 8: api.base.v1.Err.GetErr:output_type -> api.base.v1.GetErrReply
	9, // 9: api.base.v1.Err.ListErr:output_type -> api.base.v1.ListErrReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_base_v1_err_proto_init() }
func file_api_base_v1_err_proto_init() {
	if File_api_base_v1_err_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_base_v1_err_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateErrRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_base_v1_err_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateErrReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_base_v1_err_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateErrRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_base_v1_err_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateErrReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_base_v1_err_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteErrRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_base_v1_err_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteErrReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_base_v1_err_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetErrRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_base_v1_err_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetErrReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_base_v1_err_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListErrRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_base_v1_err_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListErrReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_base_v1_err_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_base_v1_err_proto_goTypes,
		DependencyIndexes: file_api_base_v1_err_proto_depIdxs,
		MessageInfos:      file_api_base_v1_err_proto_msgTypes,
	}.Build()
	File_api_base_v1_err_proto = out.File
	file_api_base_v1_err_proto_rawDesc = nil
	file_api_base_v1_err_proto_goTypes = nil
	file_api_base_v1_err_proto_depIdxs = nil
}
