// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.2
// source: api/software/v1/software.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSoftwareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateSoftwareRequest) Reset() {
	*x = CreateSoftwareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_software_v1_software_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSoftwareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSoftwareRequest) ProtoMessage() {}

func (x *CreateSoftwareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_software_v1_software_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSoftwareRequest.ProtoReflect.Descriptor instead.
func (*CreateSoftwareRequest) Descriptor() ([]byte, []int) {
	return file_api_software_v1_software_proto_rawDescGZIP(), []int{0}
}

type CreateSoftwareReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateSoftwareReply) Reset() {
	*x = CreateSoftwareReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_software_v1_software_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSoftwareReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSoftwareReply) ProtoMessage() {}

func (x *CreateSoftwareReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_software_v1_software_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSoftwareReply.ProtoReflect.Descriptor instead.
func (*CreateSoftwareReply) Descriptor() ([]byte, []int) {
	return file_api_software_v1_software_proto_rawDescGZIP(), []int{1}
}

type UpdateSoftwareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateSoftwareRequest) Reset() {
	*x = UpdateSoftwareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_software_v1_software_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSoftwareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSoftwareRequest) ProtoMessage() {}

func (x *UpdateSoftwareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_software_v1_software_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSoftwareRequest.ProtoReflect.Descriptor instead.
func (*UpdateSoftwareRequest) Descriptor() ([]byte, []int) {
	return file_api_software_v1_software_proto_rawDescGZIP(), []int{2}
}

type UpdateSoftwareReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateSoftwareReply) Reset() {
	*x = UpdateSoftwareReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_software_v1_software_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSoftwareReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSoftwareReply) ProtoMessage() {}

func (x *UpdateSoftwareReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_software_v1_software_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSoftwareReply.ProtoReflect.Descriptor instead.
func (*UpdateSoftwareReply) Descriptor() ([]byte, []int) {
	return file_api_software_v1_software_proto_rawDescGZIP(), []int{3}
}

type DeleteSoftwareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteSoftwareRequest) Reset() {
	*x = DeleteSoftwareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_software_v1_software_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSoftwareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSoftwareRequest) ProtoMessage() {}

func (x *DeleteSoftwareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_software_v1_software_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSoftwareRequest.ProtoReflect.Descriptor instead.
func (*DeleteSoftwareRequest) Descriptor() ([]byte, []int) {
	return file_api_software_v1_software_proto_rawDescGZIP(), []int{4}
}

type DeleteSoftwareReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteSoftwareReply) Reset() {
	*x = DeleteSoftwareReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_software_v1_software_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSoftwareReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSoftwareReply) ProtoMessage() {}

func (x *DeleteSoftwareReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_software_v1_software_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSoftwareReply.ProtoReflect.Descriptor instead.
func (*DeleteSoftwareReply) Descriptor() ([]byte, []int) {
	return file_api_software_v1_software_proto_rawDescGZIP(), []int{5}
}

type GetSoftwareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetSoftwareRequest) Reset() {
	*x = GetSoftwareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_software_v1_software_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSoftwareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSoftwareRequest) ProtoMessage() {}

func (x *GetSoftwareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_software_v1_software_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSoftwareRequest.ProtoReflect.Descriptor instead.
func (*GetSoftwareRequest) Descriptor() ([]byte, []int) {
	return file_api_software_v1_software_proto_rawDescGZIP(), []int{6}
}

type GetSoftwareReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetSoftwareReply) Reset() {
	*x = GetSoftwareReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_software_v1_software_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSoftwareReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSoftwareReply) ProtoMessage() {}

func (x *GetSoftwareReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_software_v1_software_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSoftwareReply.ProtoReflect.Descriptor instead.
func (*GetSoftwareReply) Descriptor() ([]byte, []int) {
	return file_api_software_v1_software_proto_rawDescGZIP(), []int{7}
}

type ListSoftwareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListSoftwareRequest) Reset() {
	*x = ListSoftwareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_software_v1_software_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSoftwareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSoftwareRequest) ProtoMessage() {}

func (x *ListSoftwareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_software_v1_software_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSoftwareRequest.ProtoReflect.Descriptor instead.
func (*ListSoftwareRequest) Descriptor() ([]byte, []int) {
	return file_api_software_v1_software_proto_rawDescGZIP(), []int{8}
}

type ListSoftwareReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListSoftwareReply) Reset() {
	*x = ListSoftwareReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_software_v1_software_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSoftwareReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSoftwareReply) ProtoMessage() {}

func (x *ListSoftwareReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_software_v1_software_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSoftwareReply.ProtoReflect.Descriptor instead.
func (*ListSoftwareReply) Descriptor() ([]byte, []int) {
	return file_api_software_v1_software_proto_rawDescGZIP(), []int{9}
}

var File_api_software_v1_software_proto protoreflect.FileDescriptor

var file_api_software_v1_software_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x73, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0f, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x76,
	0x31, 0x22, 0x17, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x66, 0x74, 0x77,
	0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x17, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x66, 0x74, 0x77,
	0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x17, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x6f, 0x66, 0x74, 0x77,
	0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x53, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x14, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x6f,
	0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x15, 0x0a, 0x13, 0x4c,
	0x69, 0x73, 0x74, 0x53, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6f, 0x66, 0x74, 0x77, 0x61,
	0x72, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xdb, 0x03, 0x0a, 0x08, 0x53, 0x6f, 0x66, 0x74,
	0x77, 0x61, 0x72, 0x65, 0x12, 0x5e, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6f,
	0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x12, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x6f, 0x66,
	0x74, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53,
	0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x5e, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x6f,
	0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x12, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x6f, 0x66,
	0x74, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53,
	0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x5e, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x6f,
	0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x12, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x6f, 0x66,
	0x74, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53,
	0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x55, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x66, 0x74, 0x77,
	0x61, 0x72, 0x65, 0x12, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x6f, 0x66, 0x74, 0x77, 0x61,
	0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73,
	0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x6f,
	0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x58, 0x0a, 0x0c, 0x4c,
	0x69, 0x73, 0x74, 0x53, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x12, 0x24, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x73, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x53, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x33, 0x0a, 0x0f, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x6f, 0x66,
	0x74, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x1e, 0x73, 0x74, 0x62, 0x2d,
	0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x6f, 0x66, 0x74,
	0x77, 0x61, 0x72, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_software_v1_software_proto_rawDescOnce sync.Once
	file_api_software_v1_software_proto_rawDescData = file_api_software_v1_software_proto_rawDesc
)

func file_api_software_v1_software_proto_rawDescGZIP() []byte {
	file_api_software_v1_software_proto_rawDescOnce.Do(func() {
		file_api_software_v1_software_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_software_v1_software_proto_rawDescData)
	})
	return file_api_software_v1_software_proto_rawDescData
}

var file_api_software_v1_software_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_software_v1_software_proto_goTypes = []interface{}{
	(*CreateSoftwareRequest)(nil), // 0: api.software.v1.CreateSoftwareRequest
	(*CreateSoftwareReply)(nil),   // 1: api.software.v1.CreateSoftwareReply
	(*UpdateSoftwareRequest)(nil), // 2: api.software.v1.UpdateSoftwareRequest
	(*UpdateSoftwareReply)(nil),   // 3: api.software.v1.UpdateSoftwareReply
	(*DeleteSoftwareRequest)(nil), // 4: api.software.v1.DeleteSoftwareRequest
	(*DeleteSoftwareReply)(nil),   // 5: api.software.v1.DeleteSoftwareReply
	(*GetSoftwareRequest)(nil),    // 6: api.software.v1.GetSoftwareRequest
	(*GetSoftwareReply)(nil),      // 7: api.software.v1.GetSoftwareReply
	(*ListSoftwareRequest)(nil),   // 8: api.software.v1.ListSoftwareRequest
	(*ListSoftwareReply)(nil),     // 9: api.software.v1.ListSoftwareReply
}
var file_api_software_v1_software_proto_depIdxs = []int32{
	0, // 0: api.software.v1.Software.CreateSoftware:input_type -> api.software.v1.CreateSoftwareRequest
	2, // 1: api.software.v1.Software.UpdateSoftware:input_type -> api.software.v1.UpdateSoftwareRequest
	4, // 2: api.software.v1.Software.DeleteSoftware:input_type -> api.software.v1.DeleteSoftwareRequest
	6, // 3: api.software.v1.Software.GetSoftware:input_type -> api.software.v1.GetSoftwareRequest
	8, // 4: api.software.v1.Software.ListSoftware:input_type -> api.software.v1.ListSoftwareRequest
	1, // 5: api.software.v1.Software.CreateSoftware:output_type -> api.software.v1.CreateSoftwareReply
	3, // 6: api.software.v1.Software.UpdateSoftware:output_type -> api.software.v1.UpdateSoftwareReply
	5, // 7: api.software.v1.Software.DeleteSoftware:output_type -> api.software.v1.DeleteSoftwareReply
	7, // 8: api.software.v1.Software.GetSoftware:output_type -> api.software.v1.GetSoftwareReply
	9, // 9: api.software.v1.Software.ListSoftware:output_type -> api.software.v1.ListSoftwareReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_software_v1_software_proto_init() }
func file_api_software_v1_software_proto_init() {
	if File_api_software_v1_software_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_software_v1_software_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSoftwareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_software_v1_software_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSoftwareReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_software_v1_software_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSoftwareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_software_v1_software_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSoftwareReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_software_v1_software_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSoftwareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_software_v1_software_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSoftwareReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_software_v1_software_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSoftwareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_software_v1_software_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSoftwareReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_software_v1_software_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSoftwareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_software_v1_software_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSoftwareReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_software_v1_software_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_software_v1_software_proto_goTypes,
		DependencyIndexes: file_api_software_v1_software_proto_depIdxs,
		MessageInfos:      file_api_software_v1_software_proto_msgTypes,
	}.Build()
	File_api_software_v1_software_proto = out.File
	file_api_software_v1_software_proto_rawDesc = nil
	file_api_software_v1_software_proto_goTypes = nil
	file_api_software_v1_software_proto_depIdxs = nil
}
