// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"go.opentelemetry.io/otel/sdk/trace"
	"stb-library/app/software/internal/biz"
	"stb-library/app/software/internal/conf"
	"stb-library/app/software/internal/data"
	"stb-library/app/software/internal/server"
	"stb-library/app/software/internal/sgin"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, office *conf.Office, tracerProvider *trace.TracerProvider) (*kratos.App, func(), error) {
	engine := sgin.NewGinEngine()
	hub := sgin.NewChatSocketfunc()
	httpServer := server.NewHTTPServer(confServer, engine, hub)
	defaultFileDir, err := sgin.ConstructorDefaultDir()
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	codeRepo := data.NewCodeRepo(dataData)
	codeUseCase := biz.NewCodeCase(codeRepo, office)
	sginSgin := sgin.NewSgin(defaultFileDir, engine, codeUseCase)
	grpcServer := server.NewGRPCServer(confServer, tracerProvider, sginSgin)
	app := newApp(httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
